/**
 * generated by Xtext
 */
package com.lowcoupling.dotEditor.validation;

import com.lowcoupling.dotEditor.dot.DotPackage;
import com.lowcoupling.dotEditor.validation.AbstractDotValidator;
import org.eclipse.emf.common.util.URI;
import org.eclipse.ocl.examples.xtext.completeocl.validation.CompleteOCLEObjectValidator;
import org.eclipse.xtext.validation.EValidatorRegistrar;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DotValidator extends AbstractDotValidator {
  private DotPackage ePackage;
  
  private URI oclURI;
  
  public void register(final EValidatorRegistrar registrar) {
    super.register(registrar);
    this.ePackage = DotPackage.eINSTANCE;
    URI _createPlatformResourceURI = URI.createPlatformResourceURI(
      "/com.lowcoupling.dotEditor/src/com/lowcoupling/dotEditor/dot.ocl", true);
    this.oclURI = _createPlatformResourceURI;
    CompleteOCLEObjectValidator _completeOCLEObjectValidator = new CompleteOCLEObjectValidator(this.ePackage, this.oclURI);
    registrar.register(this.ePackage, _completeOCLEObjectValidator);
  }
}
