/*
 * generated by Xtext
 */
package com.lowcoupling.dotEditor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DotRuntimeModule extends com.lowcoupling.dotEditor.AbstractDotRuntimeModule {

}
