/**
 * generated by Xtext
 */
package com.lowcoupling.dotEditor.ui.contentassist;

import com.lowcoupling.dotEditor.ui.contentassist.AbstractDotProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DotProposalProvider extends AbstractDotProposalProvider {
}
