/*
 * generated by Xtext
 */
package com.lowcoupling.dotEditor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.lowcoupling.dotEditor.ui.internal.DotActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DotActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DotActivator.getInstance().getInjector(DotActivator.COM_LOWCOUPLING_DOTEDITOR_DOT);
	}
	
}
