/*
* generated by Xtext
*/
package com.lowcoupling.dotEditor;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DotUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.lowcoupling.dotEditor.ui.internal.DotActivator.getInstance().getInjector("com.lowcoupling.dotEditor.Dot");
	}
	
}
