/*
 * generated by Xtext
 */
package com.lowcoupling.dotEditor.validation

import org.eclipse.xtext.validation.EValidatorRegistrar
import com.lowcoupling.dotEditor.dot.DotPackage
import org.eclipse.emf.common.util.URI
import org.eclipse.ocl.examples.xtext.completeocl.validation.CompleteOCLEObjectValidator;

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class DotValidator extends AbstractDotValidator {
	
	DotPackage ePackage
	
	URI oclURI
	
	override register(EValidatorRegistrar registrar) {
		super.register(registrar);
		ePackage = DotPackage.eINSTANCE;
        oclURI = URI.createPlatformResourceURI(
            "/com.lowcoupling.dotEditor/src/com/lowcoupling/dotEditor/dot.ocl", true);
        registrar.register(ePackage,
            new CompleteOCLEObjectValidator(ePackage, oclURI));
    
	}
	
	
       
}
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
