/*
 * generated by Xtext
 */
package com.lowcoupling.dotEditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DotUiModule extends com.lowcoupling.dotEditor.ui.AbstractDotUiModule {
	public DotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
